network:
    version: 1
    config:
        - type: physical
          name: ens32
          subnets:
              - type: static
                address: 192.168.1.105/24
                gateway: 192.168.1.1
        - type: nameserver
          address:
              - 1.1.1.1
              - 1.0.0.1
